# Generated by Django 5.0.6 on 2024-10-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0013_alter_patient_treatment_details_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='patient_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_treatment_images',
            name='patient_id',
            field=models.BigIntegerField(),
        ),
    ]
