# Generated by Django 5.0.6 on 2024-10-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0014_alter_patient_treatment_details_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_treatment_images',
            name='treatment_id',
            field=models.BigIntegerField(),
        ),
    ]
