# Generated by Django 5.0.6 on 2024-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0016_rename_weigth_patient_treatment_details_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_treatment_details',
            name='blood_pressure',
            field=models.CharField(max_length=8),
        ),
    ]
